<div id="navigation">
	<div class="navitem" style="border-left:none"><a href="index.php?action=home">Home</a></div>
    <div class="navitem"><a href="reservationform.php">News</a></div>
	 <div class="navitem"><a href="cancellation.php">Entertainment</a></div>
    <div class="navitem"><a href="viewcontact.php">Sports</a></div>
    <div class="navitem"><a href="updatecontactform.php">Music</a></div>
   
    <div class="navitem"><a href="logout.php">Logout</a></div>
</div>
